[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "windlast-core"
version = "0.1.0"
description = "Kernlogik Windlast"
requires-python = ">=3.13"

[tool.setuptools.packages.find]
include = ["windlast_CORE*"]
